### PR TITLE
Added lightweight logging class.

### PR DESCRIPTION
**Pull request by NamStalker**
Implemented lightweight logging class to log when the HUD is enabled or disabled.
Created for stale issue #4

### CODE REVIEW

**Comment by justalemon** [comment]
I was thinking on ditching the custom logging idea. After all, a message is printed during the loading and abort/close in `ScriptHookVDotNet2.log`:
```
[19:27:41] [DEBUG] Instantiating script 'GGO.Singleplayer.Main+GGO' in script domain 'ScriptDomain_F9EE2610' ...
[19:27:44] [DEBUG] Started script 'GGO.Singleplayer.Main+GGO'.
```
The errors are going to end up in in the same file in the case of an exeption.

What do you think?

**Comment by NamStalker** [comment]
I would agree with you that for instantiation and errors, ScriptHookVDotNet2.log should suffice. 

The only reason to keep a custom logger is if exception handling is implemented in an area and we want to log those errors without crashing the HUD. 
(I.e. when Images.GetWeaponImage() is called, if no resource is found to match the weapon name, it simply returns, but a custom logging class could return what weapon is missing and it could be more easily added.) But there are not many cases like this as of now.

**Comment by justalemon** [comment]
Yeah, once I start porting the mod to FiveM we are going to need per-player logging and related stuff.

I'm going to keep this open as a reminder.

**Comment by justalemon** [comment]
I have added a more or less clean logging class in daf517f8728c059ee4cc079e7c399e32723b5847 that prints the raw configuration values if the debug mode is enabled.

**Pull request closed without merging**
