### PR TITLE
Performance and general improvements

### PR DESCRIPTION
**Pull request by Jitnaught**
* Performance improvements to ped processing.
* Fixed performance drop caused by copying images from resources every time they needed to be drawn.
* Fixed inventory displaying while using a controller when aiming a gun in a vehicle, or turning in an aircraft.

Before this commit my FPS could drop 20-30 FPS when many images were drawn on the screen (such as when many dead peds are in your view). Now my FPS doesn't drop at all.

### CODE REVIEW

**Comment by Jitnaught** [comment]
Just realized the images are no longer in the project, so they aren't available for automatic builds. I'm not familiar with AppVeyor so I don't know how those images could be included in the artifact's archive file.

**Comment by justalemon** [comment]
Some stuff:

- I have pending changes on a separate branch (rewriting the config system primarily), I'm going to wait until that is finished.
- Because of this, the images need to be on a subdirectory ("scripts\\GGO\\Images", for example) so they don't "collide" with the configuration files.
- The AppVeyor build failed but is shown as succeeded, so...

**Comment by Jitnaught** [comment]
* Okay.
* I will change the paths. 
* The AppVeyor should have failed, because I just found errors I missed somehow. Will fix these. GitHub says only the CodeFactor failed though.

**Comment by justalemon** [comment]
I have added my changes and this is what a copy of GGO looks like now:
image
For the scripts folder and:
image
For the GGO folder.

Once you have merged ffe78c3cfe128d3a5e21b6e921b250f4ade7f069 the AppVeyor build should work correctly.

**Comment by justalemon** [comment]
If you don't want to fix the merge conflicts, I can rebase the changes on my side or add the code manually and give credit via [Co-authored-by](https://help.github.com/articles/creating-a-commit-with-multiple-authors/).

**Comment by Jitnaught** [comment]
I fixed the errors I didn't see earlier (including the CodeFactor check failure), added the images back, made it so the images are copied to the build folder when compiling, and fixed the image paths.

Doesn't merge anymore due to conflicts though.

**Comment by justalemon** [comment]
Just added the code on the following commits (with some tweaks):

* Ped Processing: e43bdc06026ad0d4dd77d3698973d9e7d642dc3c
* Image copy fix: 193f91b07967d1df8daef31151f09f471399e347
* Inventory-with-controller fix: bfef0c6967897cb640a85dd603bf788c8f43aafd

The commits are marked as [created by you](https://github.com/justalemon/GGOV/commits?author=Jitnaught), so that should not be a problem.

Thanks for contributing!

**Pull request closed without merging**
